### ISSUE TITLE
Once Phone is Opened, No Apps are Accessible!

### ISSUE THREAD

**Issue by dylan-digi** [CritteRo/scalePhone#9]
Edit:  crit-phone is required, this resource is just a framework. My apologies!
Disregard the stuff below:

Context: 
**Fresh install on a Vanilla FX Server.** 

Server Build Number: 
**2944**

Error in Console:
```
MainThrd/ ^1SCRIPT ERROR: @scalePhone/client/apps/cl_phone_app_homepage.lua:79: attempt to index a nil value (field '?')^7
[  72897031] [b2944_GTAProce]             MainThrd/ ^3> handler^7 (^5@scalePhone/client/apps/cl_phone_app_homepage.lua^7:79)
[  72897031] [b2944_GTAProce]             MainThrd/ ^3> ref^7 (^5@scalePhone/client/cl_phone_handle.lua^7:187)
```
This will loop in the console until the phone is closed. No apps are accessible.

Result In-game:

https://github.com/CritteRo/scalePhone/assets/42525565/c2f1b40a-4b3b-4757-bc44-8018257819d8

\

**Comment by CritteRo** [comment]
Glad you found the fix! Closing the defect.
